name: thepeer_flutter
description: Official plugin for using Thepeer SDK with flutter https://thepeer.co
version: 2.0.11
homepage: https://github.com/thepeerstack/flutter-sdk

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_android:
    sdk: flutter
  connectivity_plus: ^3.0.2
  equatable: ^2.0.3
  flutter_svg: ^1.0.3
  gap: 
    git:
      url: https://github.com/TimWhiting/gap
  modal_bottom_sheet: ^3.0.0-pre
  webview_flutter: ^4.0.6
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/thepeer_flutter/assets/images/logo.png
    - packages/thepeer_flutter/assets/images/close.svg
    - packages/thepeer_flutter/assets/images/warning_badge.svg

  fonts:
    - family: Gilroy-Bold
      fonts:
        - asset: packages/thepeer_flutter/assets/fonts/Gilroy-Bold.ttf
          weight: 700

    - family: Gilroy-SemiBold
      fonts:
        - asset: packages/thepeer_flutter/assets/fonts/Gilroy-SemiBold.ttf
          weight: 600

    - family: Gilroy-Medium
      fonts:
        - asset: packages/thepeer_flutter/assets/fonts/Gilroy-Medium.ttf
          weight: 500
